command_timeout = 3000

right_format = "$git_branch"

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[git_branch]
format = "[$symbol$branch]($style) "

[gcloud]
disabled = true

[docker_context]
disabled = true

[terraform]
disabled = true
