name: Check install script

# feature/* ブランチへの Push 時に実行
on:
  push:
    branches:
      - feature/*

jobs:
  # Ubuntu 環境での動作確認
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: Install dotfiles
        run: |
          echo $SHELL
          yes | ./bin/ubuntu_install.sh \
          && ls -la ~/ | grep .zshrc

  # macOS 環墨での動作確認
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v1
      - name: Install dotfiles
        run: |
          yes | ./bin/mac_install.sh \
          && ls -la ~/ | grep .zshrc
