name: Check install script

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: Install dotfiles
        run: |
          sed -i '1s/^.*$/#!\/bin\/bash/' ./bin/install.sh
          cat ./bin/install.sh
          bash ./bin/install.sh
