name: Check install script on Ubuntu and macOS

# feature/* ブランチへの Push 時に実行
on:
  push:
    branches:
      - feature/*

  # ARM64 の Ubuntu 環境での動作確認
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    container: ubuntu:22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo

      - name: Install dotfiles
        run: |
          echo $SHELL
          uname -a
          yes | ./bin/ubuntu_install.sh \
          && ls -la ~/ | grep .zshrc

  # macOS 環墨での動作確認
  macos:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dotfiles
        run: |
          yes | ./bin/mac_install.sh \
          && ls -la ~/ | grep .zshrc
